name: test-dependor
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test-packages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21.0"
      - name: test packages
        run: make test
